In [6]:
import pandas as pd

In [15]:
import random
lst = ['robot'] * 10
lst += ['human'] * 10
random.shuffle(lst)
data = pd.DataFrame({'whoAmI':lst})
data.head()

  whoAmI
0  human
1  robot
2  robot
3  human
4  human

In [42]:
data[data['whoAmI']=='human'],[data['whoAmI']=='robot']
data

   whoAmI human robot
0   human  True   NaN
1   robot   NaN  True
2   robot   NaN  True
3   human  True   NaN
4   human  True   NaN
5   human  True   NaN
6   robot   NaN  True
7   robot   NaN  True
8   robot   NaN  True
9   human  True   NaN
10  human  True   NaN
11  robot   NaN  True
12  robot   NaN  True
13  robot   NaN  True
14  human  True   NaN
15  robot   NaN  True
16  human  True   NaN
17  robot   NaN  True
18  human  True   NaN
19  human  True   NaN